name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: cmake -DCMAKE_BUILD_TYPE=Release .
    - name: make
      run: cmake --build . --target ALL_BUILD --config Release
